### ISSUE TITLE
Native dependency cmake needed?

### ISSUE THREAD

**Issue by Siilwyn** [twilco/kosmonaut#9]
Followed the readme: Cloned the project and ran `cargo build` using rust `1.47.0-nightly` on Ubuntu 20.04 which returns the following error:
```
error: failed to run custom build command for `expat-sys v2.1.6`

Caused by:
  process didn't exit successfully: `/home/siilwyn/codeground/a-forks/kosmonaut/target/debug/build/expat-sys-bf2c8658b355277e/build-script-build` (exit code: 101)
  --- stdout
  running: "cmake" "/home/siilwyn/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/expat-sys-2.1.6/expat" "-DBUILD_shared=OFF" "-DBUILD_tools=OFF" "-DBUILD_examples=OFF" "-DBUILD_tests=OFF" "-DCMAKE_INSTALL_PREFIX=/home/siilwyn/codeground/a-forks/kosmonaut/target/debug/build/expat-sys-c8008326b5972c6b/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"

  --- stderr
  thread 'main' panicked at '
  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?
```

Guess I first need to run `apt install cmake`? If so it would be good to add this to the readme perhaps? An even better alternative would be to swap the dependency to a full Rust one so no native external dependency is needed, if possible.

**Comment by twilco** [comment]
You're right — `cmake` will be required, along with a few other dependencies.  I've updated the readme and listed all other packages required for an Ubuntu build with this commit: https://github.com/twilco/kosmonaut/commit/a871c49df2d672fb2a4a2376d113876e86d562b1

I believe all of these are required because of Kosmonaut's use of FreeType for text rendering.  I'd love to explore pure-Rust alternatives down the road.

Feel free to close this out if it resolves your issue and thanks for reporting!

**Comment by Siilwyn** [comment]
Awesome thanks for the response @twilco!
Let's continue the discussion in #10. :)
